api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "529f6a244dc15b38ee1522b640fef837a052c98902874dc6fe9d8ca7d418025d"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.132.tar.gz"
    source_sha256 = "3a2d3c660dce4c4081e4a57a432c60747945cceead6161638e91530e006504d6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.132/dep-0.0.132.tgz"
    version = "0.0.132"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-compiler"
    sha256 = "016ea37701e2dc17f47c70294870926bfee09649f1ea4b4a2166300f2edcb570"
    source = "https://github.com/paketo-buildpacks/go-compiler/archive/v0.0.145.tar.gz"
    source_sha256 = "03a1ebeb53d7d47e4be4962230b9a326a3a97684e766e42015f68e0037792f9c"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-compiler/releases/download/v0.0.145/go-compiler-0.0.145.tgz"
    version = "0.0.145"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "05ff0dc79a58bf30886d0c7c377c51db1f932f53c671260177e95eba565d3117"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.122.tar.gz"
    source_sha256 = "d6c9934ce6abf34e2f83e190f4e25e20ff22f4fe3a275744a418b4f747421677"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.122/go-mod-0.0.122.tgz"
    version = "0.0.122"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.145"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.122"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.145"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.132"
