api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dep"
    sha256 = "529f6a244dc15b38ee1522b640fef837a052c98902874dc6fe9d8ca7d418025d"
    source = "https://github.com/paketo-buildpacks/dep/archive/v0.0.132.tar.gz"
    source_sha256 = "3a2d3c660dce4c4081e4a57a432c60747945cceead6161638e91530e006504d6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/dep/releases/download/v0.0.132/dep-0.0.132.tgz"
    version = "0.0.132"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-compiler"
    sha256 = "3fa380600c1b7c1787688bb8d10ecef60fe018f0d1b3ebfb20caedcd0425460d"
    source = "https://github.com/paketo-buildpacks/go-compiler/archive/v0.0.142.tar.gz"
    source_sha256 = "1220064de784de08fc72c5c69896da2138b31ff7be332cc44b633f64cea39682"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-compiler/releases/download/v0.0.142/go-compiler-0.0.142.tgz"
    version = "0.0.142"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/go-mod"
    sha256 = "b8afcb393bd0820cff25d19e762225bb9b1523c96465b692cdacb262935cb3e2"
    source = "https://github.com/paketo-buildpacks/go-mod/archive/v0.0.121.tar.gz"
    source_sha256 = "f67573cb308383fab462d968b47e4a2b03257d4010bff7815ac9802105e3d8a5"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny", "io.paketo.stacks.tiny"]
    uri = "https://github.com/paketo-buildpacks/go-mod/releases/download/v0.0.121/go-mod-0.0.121.tgz"
    version = "0.0.121"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.142"

  [[order.group]]
    id = "paketo-buildpacks/go-mod"
    version = "0.0.121"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-compiler"
    version = "0.0.142"

  [[order.group]]
    id = "paketo-buildpacks/dep"
    version = "0.0.132"
